### ISSUE TITLE
As a new game developer, I want a small, hackable example of a game loop so it's easy to get started without hitting the tyranny of the blank page

### ISSUE THREAD

**Issue by modeswitch** [mozilla/WebGameStub#1]
- Should be small in size (~500 lines of JS?)
  - One possibility:
    - JS: https://github.com/lostdecade/simple_canvas_game/tree/256d456f6dd5ceb6d1825a9fcdea0e046fd47857
    - Tutorial: http://www.lostdecadegames.com/demos/simple_canvas_game/
    - Game: http://www.lostdecadegames.com/demos/simple_canvas_game/
    - License question: https://github.com/lostdecade/simple_canvas_game/issues/1
- Should be a side-scroll (platformer) or top-down

**Comment by dmose** [comment]
From twitter, we have permission from the Lost Decade Games guys to use simple_canvas_game:

https://twitter.com/richtaur/status/217781280690020353

W00t!

**Comment by dmose** [comment]
First cut of this is done; thanks, David!  Next steps will be done in upcoming user stories.
