### ISSUE TITLE
Deploy simple-canvas-game example to github pages

### ISSUE THREAD

**Issue by dmose** [mozilla/WebGameStub#22]
It would be impolite to risk melting Lost Decade's servers.  Also, this is a good chance to exercise our code in-situ before shipping.

We may also want to frame it in the README.

**Comment by modeswitch** [comment]
Please update the manifests to point to the hosted version of the game. The manifests are using example.com URLs right now.

**Comment by dmose** [comment]
Found two major problems in doing this: 
- appcache support has issues, so I've tweaked the README to recommend 'volo build' as the build step, and filed issue 40 to investigate
- an errant .gitignore in the img/ directory was causing images not to be deployed to github

I also cleaned up the img/ directory in the the stub, as it had leftovers from the examples game.

**Comment by dmose** [comment]
I've got the example game deployed to dmose.github.com/WebGameStub and referenced that way from the README.md.  Longer term, this should be deployed to mozilla.github.com/WebGameStub, but I haven't tweaked the mozilla-wide pages before, and wanted to be a bit careful when doing this, rather than slamming it in the morning before a demo.  I've filed issue #43 to track that.
