### ISSUE TITLE
As a game developer, I want the simple-canvas-game example to be installable as an app in Chrome and Firefox

### ISSUE THREAD

**Issue by modeswitch** [mozilla/WebGameStub#27]
- README.md should be up-to-date
  *\* for best results use Firefox 16 nightly builds; earlier versions may not work at all 
  *\* clarify that a web server must be used and that file: URLs will not work
  **\* explain how to test with volo
- manifests for both browsers should be up-to-date
- developers should be credited appropriately in all manifests
- HTML5 icon should be work

**Comment by dmose** [comment]
A fair bit of this is implemented in my revised-web-app topic branch.  Probably all of the conversation points should be verified before making a pull request (some of them aren't yet done).
