### ISSUE TITLE
As a game developer, I want the game stub to be installable as an app in Chrome and Firefox

### ISSUE THREAD

**Issue by modeswitch** [mozilla/WebGameStub#28]
- HTML5 icon should work
- using ghdeploy should yield an app that installs and tests remotely from github
- README.md should guide me through setting up and installing my game as an app (maybe borrow text from example)
  *\* for best results use Firefox 16 nightly builds; earlier versions may not work at all

**Comment by dmose** [comment]
Merged to develop; no review.
