### ISSUE TITLE
As a less artistic game developer, I want a ready source of nice-looking art from the beginning so that I can make my game look more polished

### ISSUE THREAD

**Issue by modeswitch** [mozilla/WebGameStub#4]
- http://lpc.opengameart.org/
- http://www.lostgarden.com/2007/05/dancs-miraculously-flexible-game.html
- http://youcanmakevideogames.com/
- Links from the README

**Comment by dmose** [comment]
Paired with dperit on this, the README's all set.  The youcanmakevideogames page had no 2d art, and we removed the .textile README as part of this commit too.
