### ISSUE TITLE
As a new game developer, I want to be able to visit a web page where I can download the template and read some getting started docs so that I know what the template is, why I want it, and how to get started

### ISSUE THREAD

**Issue by modeswitch** [mozilla/WebGameStub#5]
- Incorporiate relevant info from old template README.md
- This can be the github README.md page

**Comment by dmose** [comment]
I've got an updated outline at https://gladius.etherpad.mozilla.org/54.  I feel like the first-paragraph sell is a good start.  The next two paragraphs I think are good ways to show the thing in action, but may expand to a lot of text.  It could be refactoring that text by moving some of it to another page and replacing some of it with a screencast could be the way to go.  Feel free to pair on / run with this in the morning before I'm in.

**Comment by dmose** [comment]
FWIW, from looking at the HTML5 boilerplate pages, I think we shouldn't hesitate to break this out into multiple pages if that's the right thing to do.

**Comment by dmose** [comment]
Pull request containing implementation merged (thanks dperit!).  Subsequent README work captured in issue 20.
