### ISSUE TITLE
not clear what "update(delta / 1000)" does

### ISSUE THREAD

**Issue by dmose** [mozilla/WebGameStub#51]
This is feedback from @fwenzel from MDN Hack Day.  Part of this is probably due to the fact that the formal parameter name to update is "modifier", when it should really be something like timeDeltaInSeconds.  We might also want a comment about Date.now returning milliseconds.

**Comment by fwenzel** [comment]
I guess I did understand that it's turning milliseconds into seconds, but I still don't understand why that's useful for me in the update method.

**Comment by dmose** [comment]
Ah, fair point.  So you if you have fast moving graphics, you'd use it to calculate how far (for example) your bullet should have moved since the last frame was rendered so that it will appear to be moving at a constant velocity.
