### ISSUE TITLE
Use requestAnimationFrame, but fall back to setInterval

### ISSUE THREAD

**Issue by fwenzel** [mozilla/WebGameStub#55]
WGS uses setInterval for now, prolly because requestAnimationFrame isn't universally supported yet. It should probably use req.Anim.Fr. but fall back to setInterval.

Example:
https://github.com/fwenzel/serpent/blob/ae745680590437b651d1f4279ba242fbb906a69c/www/js/app.js#L8

Note, I am using 1/60s for setInterval, not sure if that's a good idea or if I should just use setInterval 1 and let the browser iterate as fast as it can.

**Comment by dmose** [comment]
I get the sense that 1/60 of a second is pretty reasonable.  https://bugzilla.mozilla.org/show_bug.cgi?id=731974#c30 is relevant here, and for anyone who feels like slogging through the whole bug, there's a lot of good info there.

**Comment by fwenzel** [comment]
Interesting: That means the fallback could be made smarter, we might have to use the then vs now logic that we already use for the update() function and use that to decide how long setInterval should be. The one-liner fallback I use on serpent works well, but every frame will not take 1/60s, but instead it'll take 1/60s + however long the loop iteration took. (I might be overthinking it though. Try playing serpent on Safari and you'll see that the simple fallback works very well for my particular app).

**Comment by dmose** [comment]
You're quite right that that could make a difference for twitchier games.
