### ISSUE TITLE
As a new game developer, it should be easy to get started publishing my game to web marketplaces so that I can monetize my work

### ISSUE THREAD

**Issue by modeswitch** [mozilla/WebGameStub#7]
- Mozilla Markeplace
- Chrome Marketplace
- Update tutorial to show how to publish to marketplaces

**Comment by modeswitch** [comment]
Mozilla Marketplace example: https://github.com/dmose/focusTimer/commit/bc2f492f16fcb0dc875a7aa1fb237b37df2abb96

**Comment by modeswitch** [comment]
Chrome web store docs: https://developers.google.com/chrome/web-store/docs/get_started_simple

**Comment by dmose** [comment]
Before we can close this user story, we still need to get the icon working in Firefox, spinout new users stories for code/test workflow, and make a decision about what to do for this release and spin out a new user story for that.
